name: Label Approved

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  # TODO: fix this
  pull_request:

permissions:
  pull-requests: write

jobs:
  label-approved:
    if: github.repository_owner == 'fastapi'
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: actions/cache@v4
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-github-actions-${{ env.pythonLocation }}-${{ hashFiles('requirements-github-actions.txt') }}-v01
    - name: Install GitHub Actions dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install -r requirements-github-actions.txt
    - name: Label Approved
      run: python ./scripts/label_approved.py
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG: >
          {
            "approved-1":
              {
                "number": 1,
                "await_label": "awaiting-review"
              }
          }
